language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0

before_script:
 - composer self-update --quiet
 - composer install --prefer-source

script:
 - vendor/bin/phpunit

notifications:
  irc: "irc.freenode.org#phpdocumentor"
  email:
    - mike.vanriel@naenius.com
    - ashnazg@php.net
